## Secunda (тестовое задание)

### Часть 1
1. Составить реестр, в который войдут все клиенты из отчета 1
2. Недостающие поля взять из отчета 2
3. Из сформированного реестра исключить клиентов из вкладки "цессия" и со статусом "банкрот", "погашен", "досрочно погашен"
4. Из полученного реестра построить сводную таблицу по регионам, количеством клиентов по регионам и суммой выданных займов по регионам

### Часть 2
1. Написать SQL запрос по отчету 2, который выведет клиентов с регионом выдачи онлайн и выданные в 2024 году
2. Написать SQL запрос по отчету 2, который выведет три поля: статус, количество клиентов в статусе, сумму выданных займов в статусе
3. Написать SQL запрос, который выведет все поля отчета 1 и отчета 2

In [1]:
import pandas as pd

In [2]:
general_ex = pd.ExcelFile('Тестовое Secunda.xlsx')

In [4]:
general_ex.sheet_names

['цессия', 'отчет 2', 'отчет 1', 'задание']

In [9]:
cessiya = general_ex.parse('цессия')
report_1 = general_ex.parse('отчет 1')
report_2 = general_ex.parse('отчет 2')

In [8]:
cessiya.head()

,Id,ContractID,Date,CessionArticleID,Amount,SellingPrice,IsOutgoing,CessionArticleID.1,Name,ProviderID
0,6,125922,2024-06-26,10,1000,0,Y,125922,1НБЦ от 21.01.2021,4
1,1,116791,2024-06-26,10,2000,0,Y,116791,1НБЦ от 21.01.2021,4
2,10,109897,2024-06-26,10,3000,0,Y,109897,1НБЦ от 21.01.2021,4
3,5432,104036,2024-06-26,10,4000,0,Y,104036,1НБЦ от 21.01.2021,4
4,7886,88259,2024-04-23,4,5000,0,Y,88259,3НБЦ от 23.03.2023,4

In [15]:
report_1.head()

,№,Номер контракта,дата выдачи,Сумма выдачи,Задолженность по ОД,Задолженность по %%,"Кол-во дней просрочки, фактическое"
0,1,3547,2023-03-23,60000,47104.16,23926.86,525
1,2,68,2022-09-30,35000,11447.66,1300.06,552
2,3,389,2022-10-28,30000,4410.20,249.72,482
3,4,1393,2022-12-20,40000,11088.24,1482.47,457
4,5,2050,2023-01-26,50000,42219.24,30483.14,609

In [16]:
report_2.head()

,NumContract,ContractID,ClientID,inner_lead_id,SubdivisionName,issueDateTimestamp,RepaymentPlanDate,LoanAmount,Status,DateStatus,SumLastPay
0,68,183,219,\N,Белгород,2022-09-30 15:18:31,2023-09-29,35000,COLLECTOR,2024-10-03 14:33:23,1950
1,91,252,291,\N,Электросталь,2022-10-04 17:40:57,2023-10-03,50000,EARLY_REPAID,2023-07-27 21:05:44,3078
2,265,774,954,\N,Вологда,2022-10-19 15:28:15,2023-06-28,25000,EARLY_REPAID,2023-05-16 16:30:05,5700
3,389,1146,1344,\N,Вологда,2022-10-28 12:44:37,2023-10-27,30000,DELINQUENT,2023-10-07 00:00:00,1200
4,457,1352,1557,\N,Белгород,2022-11-02 13:43:20,2023-07-12,30000,REPAID,2023-06-15 15:15:02,3000

### Задание 1 и 2
- Составить реестр, в который войдут все клиенты из отчета 1
- Недостающие поля взять из отчета 2

In [21]:
reestr = pd.merge(left=report_1,
                    right=report_2,
                    left_on='Номер контракта',
                    right_on='NumContract',
                    how='left')
reestr.drop(columns=['NumContract', 'LoanAmount'])

reestr.head()

Реестр

,№,Номер контракта,дата выдачи,Сумма выдачи,Задолженность по ОД,Задолженность по %%,"Кол-во дней просрочки, фактическое",NumContract,ContractID,ClientID,inner_lead_id,SubdivisionName,issueDateTimestamp,RepaymentPlanDate,LoanAmount,Status,DateStatus,SumLastPay
0,1,3547,2023-03-23,60000,47104.16,23926.86,525,3547,10614,75,12098,Электросталь,2023-03-23 13:49:12,2024-03-21,60000,COLLECTOR,2023-11-21 23:00:00,1775
1,2,68,2022-09-30,35000,11447.66,1300.06,552,68,183,219,\N,Белгород,2022-09-30 15:18:31,2023-09-29,35000,COLLECTOR,2024-10-03 14:33:23,1950
2,3,389,2022-10-28,30000,4410.20,249.72,482,389,1146,1344,\N,Вологда,2022-10-28 12:44:37,2023-10-27,30000,DELINQUENT,2023-10-07 00:00:00,1200
3,4,1393,2022-12-20,40000,11088.24,1482.47,457,1393,4157,9776,\N,Электросталь,2022-12-20 14:24:23,2023-12-19,40000,ACTIVE_SB,2023-12-12 23:00:00,3000
4,5,2050,2023-01-26,50000,42219.24,30483.14,609,2050,6127,35551,\N,Санкт-Петербург,2023-01-26 18:01:52,2024-01-25,50000,COLLECTOR,2024-12-17 15:34:37,2200

### Задание 3
- Из сформированного реестра исключить клиентов из вкладки "цессия" и со статусом "банкрот", "погашен", "досрочно погашен"

In [33]:
reestr = reestr[
    (~reestr['ContractID'].isin(cessiya['ContractID'])) &
    (~reestr['Status'].isin(['EARLY_REPAID', 'REPAID', 'BANKRUPTCY']))]

reestr.head()

,№,Номер контракта,дата выдачи,Сумма выдачи,Задолженность по ОД,Задолженность по %%,"Кол-во дней просрочки, фактическое",NumContract,ContractID,ClientID,inner_lead_id,SubdivisionName,issueDateTimestamp,RepaymentPlanDate,LoanAmount,Status,DateStatus,SumLastPay
0,1,3547,2023-03-23,60000,47104.16,23926.86,525,3547,10614,75,12098,Электросталь,2023-03-23 13:49:12,2024-03-21,60000,COLLECTOR,2023-11-21 23:00:00,1775
1,2,68,2022-09-30,35000,11447.66,1300.06,552,68,183,219,\N,Белгород,2022-09-30 15:18:31,2023-09-29,35000,COLLECTOR,2024-10-03 14:33:23,1950
2,3,389,2022-10-28,30000,4410.20,249.72,482,389,1146,1344,\N,Вологда,2022-10-28 12:44:37,2023-10-27,30000,DELINQUENT,2023-10-07 00:00:00,1200
3,4,1393,2022-12-20,40000,11088.24,1482.47,457,1393,4157,9776,\N,Электросталь,2022-12-20 14:24:23,2023-12-19,40000,ACTIVE_SB,2023-12-12 23:00:00,3000
4,5,2050,2023-01-26,50000,42219.24,30483.14,609,2050,6127,35551,\N,Санкт-Петербург,2023-01-26 18:01:52,2024-01-25,50000,COLLECTOR,2024-12-17 15:34:37,2200

### Задание 4
- Из полученного реестра построить сводную таблицу по регионам, количеством клиентов по регионам и суммой выданных займов по регионам

In [38]:
pivot_reestr = reestr.pivot_table(
    index='SubdivisionName',
    values=['Номер контракта', 'LoanAmount'],
    aggfunc={'Номер контракта':'count', 'LoanAmount': 'sum'}
).rename(columns={'LoanAmount': 'total_amount', 'Номер контракта':'count'})

pivot_reestr.head()

                 total_amount  count
SubdivisionName
Астрахань               30000      1
Белгород                65000      2
Вологда                 30000      1
Курск                   20000      1
Онлайн                  44800      5

## Часть 2

Подготовка

In [53]:
import sqlite3

conn = sqlite3.connect(':memory:')

report_2.to_sql('report_2', conn, index=False, if_exists='replace')
report_1.to_sql('report_1', conn, index=False, if_exists='replace')

def query(sql_query):
    return pd.read_sql_query(sql_query, conn)

### Задание 1
- Написать SQL запрос по отчету 2, который выведет клиентов с регионом выдачи онлайн и выданные в 2024 году

In [54]:
query('''
SELECT ClientID
FROM report_2
WHERE SubdivisionName = 'Онлайн'
      AND strftime('%Y', [issueDateTimestamp]) = '2024'
''')

   ClientID
0    327624
1    330366
2    330727
3    331276
4    331792
5    336370
6    342546
7    392176
8    361491

### Задание 2
- Написать SQL запрос по отчету 2, который выведет три поля: статус, количество клиентов в статусе, сумму выданных займов в статусе

In [65]:
query('''
SELECT Status, COUNT(ClientID) as clients, SUM(LoanAmount) as total_amount
FROM report_2
GROUP BY Status
ORDER BY COUNT(ClientID) DESC
''')

         Status  clients  total_amount
0     COLLECTOR       20        431500
1          SOLD        5        139800
2  EARLY_REPAID        4        140000
3        REPAID        3         90000
4     ACTIVE_SB        3         76000
5    DELINQUENT        2         39900
6      CANCELED        1         30000
7    BANKRUPTCY        1         36000

### Задание 3
- Написать SQL запрос, который выведет все поля отчета 1 и отчета 2 (использую LEFT JOIN и подтягиваю данные к отчет 2, если нужны все то использую RIGHT)

In [63]:
query('''
SELECT *
FROM report_2 r2
LEFT JOIN report_1 r1
    ON r2.ContractID = r1.[Номер контракта]
LIMIT 5
''')

,NumContract,ContractID,ClientID,inner_lead_id,SubdivisionName,issueDateTimestamp,RepaymentPlanDate,LoanAmount,Status,DateStatus,SumLastPay,№,Номер контракта,дата выдачи,Сумма выдачи,Задолженность по ОД,Задолженность по %%,"Кол-во дней просрочки, фактическое"
0,68,183,219,\N,Белгород,2022-09-30 15:18:31,2023-09-29 00:00:00,35000,COLLECTOR,2024-10-03 14:33:23,1950,None,None,None,None,None,None,None
1,91,252,291,\N,Электросталь,2022-10-04 17:40:57,2023-10-03 00:00:00,50000,EARLY_REPAID,2023-07-27 21:05:44,3078,None,None,None,None,None,None,None
2,265,774,954,\N,Вологда,2022-10-19 15:28:15,2023-06-28 00:00:00,25000,EARLY_REPAID,2023-05-16 16:30:05,5700,None,None,None,None,None,None,None
3,389,1146,1344,\N,Вологда,2022-10-28 12:44:37,2023-10-27 00:00:00,30000,DELINQUENT,2023-10-07 00:00:00,1200,None,None,None,None,None,None,None
4,457,1352,1557,\N,Белгород,2022-11-02 13:43:20,2023-07-12 00:00:00,30000,REPAID,2023-06-15 15:15:02,3000,None,None,None,None,None,None,None

In [58]:
report_1.head()

,№,Номер контракта,дата выдачи,Сумма выдачи,Задолженность по ОД,Задолженность по %%,"Кол-во дней просрочки, фактическое"
0,1,3547,2023-03-23,60000,47104.16,23926.86,525
1,2,68,2022-09-30,35000,11447.66,1300.06,552
2,3,389,2022-10-28,30000,4410.20,249.72,482
3,4,1393,2022-12-20,40000,11088.24,1482.47,457
4,5,2050,2023-01-26,50000,42219.24,30483.14,609